module.exports = [
  {
    id: 1,
    name: "Oscar Delgado Perez",
    email: "oscar.delgado@gmail.com",
    user_type: "Asesor",
    queries_number: "1191",
    procceses_number: "0",
    site: "Cali",
    assigned_areas: [
      "CIVIL Y NOTARIADO",
      "ADMINISTRATIVO",
      "COMERCIAL Y DE CONSUMO",
      "LABORAL Y SEGUROS",
      "FAMILIA Y SUCESIONES",
      "JUZGADOS ESPECIALES",
    ],
  },
  {
    id: 2,
    name: "Oscar Delgado Perez",
    email: "oscar.delgado@gmail.com",
    user_type: "Asesor",
    queries_number: "1191",
    procceses_number: "0",
    site: "Cali",
    assigned_areas: [
      "CIVIL Y NOTARIADO",
      "ADMINISTRATIVO",
      "COMERCIAL Y DE CONSUMO",
      "LABORAL Y SEGUROS",
      "FAMILIA Y SUCESIONES",
      "JUZGADOS ESPECIALES",
    ],
  },  
  {
    id: 3,
    name: "Oscar Delgado Perez",
    email: "oscar.delgado@gmail.com",
    user_type: "Asesor",
    queries_number: "1191",
    procceses_number: "0",
    site: "Cali",
    assigned_areas: [
      "CIVIL Y NOTARIADO",
      "ADMINISTRATIVO",
      "COMERCIAL Y DE CONSUMO",
      "LABORAL Y SEGUROS",
      "FAMILIA Y SUCESIONES",
      "JUZGADOS ESPECIALES",
    ],
  },
  {
    id: 4,
    name: "Oscar Delgado Perez",
    email: "oscar.delgado@gmail.com",
    user_type: "Asesor",
    queries_number: "1191",
    procceses_number: "0",
    site: "Cali",
    assigned_areas: [
      "CIVIL Y NOTARIADO",
      "ADMINISTRATIVO",
      "COMERCIAL Y DE CONSUMO",
      "LABORAL Y SEGUROS",
      "FAMILIA Y SUCESIONES",
      "JUZGADOS ESPECIALES",
    ],
  },
];
